version: '3.8'

services:
  backend:
    image: ai_doc_platform-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: ai-doc-platform-backend
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/generated_docs:/app/generated_docs
    env_file:
      - .env
    environment:
      - AI_API_KEY=${AI_API_KEY}
      - AI_API_ENDPOINT=${AI_API_ENDPOINT}
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ai-doc-platform-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/generated_docs:/usr/share/nginx/html/downloads
      - ./nginx/logs:/var/log/nginx
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  generated_docs:
    driver: local

networks:
  app-network:
    driver: bridge