version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: ai-doc-platform-backend
    restart: always
    volumes:
      - ./backend:/app
      - generated_docs:/app/generated_docs
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: ai-doc-platform-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    container_name: ai-doc-platform-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - generated_docs:/usr/share/nginx/html/downloads

volumes:
  generated_docs: 